# Generated by Django 2.1.3 on 2018-12-03 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('admin', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=30, verbose_name='nombre de usuario')),
                ('nombres', models.CharField(max_length=30)),
                ('a_paterno', models.CharField(max_length=30, verbose_name='apellido paterno')),
                ('a_materno', models.CharField(blank=True, max_length=30, verbose_name='apellido materno')),
                ('password', models.CharField(max_length=30, verbose_name='contraseña')),
            ],
        ),
        migrations.CreateModel(
            name='Automovil',
            fields=[
                ('placa', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=10)),
                ('tipo_vehiculo', models.CharField(choices=[('MT', 'Motocicleta'), ('AU', 'Automovil'), ('CM', 'Camioneta'), ('VN', 'Van'), ('OT', 'Otros')], max_length=2, verbose_name='tipo de vehiculo')),
                ('marca', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Cajon',
            fields=[
                ('cajon', models.AutoField(primary_key=True, serialize=False)),
                ('num_cajon', models.IntegerField(verbose_name='numero de cajón')),
                ('horario_entrada', models.DateTimeField()),
                ('horario_salida', models.DateTimeField()),
                ('disponible', models.BooleanField(default=True)),
                ('num_estacionamiento', models.IntegerField(choices=[(1, 'PRINCIPAL'), (2, 'TRASERO'), (3, 'DISCAPACITADOS PRINCIPAL'), (4, 'DISCAPACITADOS TRASERO')])),
            ],
        ),
        migrations.CreateModel(
            name='LugarAsignado',
            fields=[
                ('lugar', models.AutoField(primary_key=True, serialize=False)),
                ('horario_entrada', models.DateTimeField(verbose_name='horario de entrada')),
                ('horario_salida', models.DateTimeField(verbose_name='horario de salida')),
                ('id_cajon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Cajon')),
            ],
        ),
        migrations.CreateModel(
            name='Sancion',
            fields=[
                ('sancion', models.AutoField(primary_key=True, serialize=False)),
                ('razon', models.TextField()),
                ('fecha', models.DateTimeField(verbose_name='fecha de la sanción')),
                ('fecha_inicio', models.DateTimeField(verbose_name='fecha de inicio')),
                ('fecha_termino', models.DateTimeField(verbose_name='fecha de termino')),
                ('id_admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.Administrador')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('horario_entrada', models.DateTimeField(verbose_name='horario de entrada')),
                ('horario_salida', models.DateTimeField(verbose_name='horario de salida')),
                ('aprovada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user', models.AutoField(primary_key=True, serialize=False)),
                ('num_id', models.CharField(max_length=30, verbose_name='número identificador')),
                ('usuario', models.CharField(max_length=30, verbose_name='nombre de usuario')),
                ('nombres', models.CharField(max_length=30)),
                ('a_paterno', models.CharField(max_length=30, verbose_name='apellido paterno')),
                ('a_materno', models.CharField(blank=True, max_length=30, verbose_name='apellido materno')),
                ('password', models.CharField(max_length=30, verbose_name='contraseña')),
                ('telefono', models.CharField(max_length=30)),
                ('tipo_usuario', models.IntegerField(choices=[(1, 'Docente'), (2, 'Administrativo'), (3, 'Alumno'), (4, 'Directivo')])),
                ('discapacitado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='solicitud',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Usuario'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='id_vehiculo_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_vehiculo1_sol', to='web.Automovil'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='id_vehiculo_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_vehiculo2_sol', to='web.Automovil'),
        ),
        migrations.AddField(
            model_name='sancion',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Usuario'),
        ),
        migrations.AddField(
            model_name='lugarasignado',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Usuario'),
        ),
        migrations.AddField(
            model_name='lugarasignado',
            name='id_vehiculo_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_vehiculo1_lugar', to='web.Automovil'),
        ),
        migrations.AddField(
            model_name='lugarasignado',
            name='id_vehiculo_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_vehiculo2_lugar', to='web.Automovil'),
        ),
    ]
