# Generated by Django 2.1.3 on 2018-12-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nombres',
            field=models.CharField(max_length=30, verbose_name='nombres'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='num_id',
            field=models.CharField(max_length=30, unique=True, verbose_name='número identificador'),
        ),
    ]
